sudo: required 
dist: trusty 
language: generic 
env:
  - ROS_DISTRO="melodic"
  - ADDITIONAL_DEBS="ros-melodic-rostest ros-melodic-joy"
install:
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci  
script: 
  - .industrial_ci/ci.sh